### ISSUE TITLE
Memory is not found on source nuget repository.

### ISSUE THREAD

**Issue by gir489** [shlifedev/AmongUsMemory#24] opened 2020-09-26 03:19 UTC
The memory dependency is not a valid nuget dependency, it should be added as a compiled dependency or gitmodule from the source repo.

**Comment by Paffo** [comment] 2020-09-26 03:39
The memory Nuget was recently removed, you can remove it from dependancies and add the dll as resource manually.

**Comment by Tiny-Lamma** [comment] 2020-09-27 14:58
Just get rid of this file AmongUsMemory/packages.config (memory Nuget isn't used and this will throw the error, just include the memory.dll and this will run fine).

**Comment by shlifedev** [comment] 2020-09-29 03:01
Deleted memory.dll from nuget. so i will add memory.dll my project self.

**Comment by SaSiNO97** [comment] 2020-12-26 02:46
You can now install it again from NuGet, after removing it from packages.config

**Comment by mariomurrent-softwaresolutions** [comment] 2021-01-02 22:40
Duplicate of [#19](https://github.com/shlifedev/AmongUsMemory/issues/19)

**Closed** 2021-01-04 12:16 UTC
